# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below

$mainMod = SUPER

# Move focus  with mainMod + vim keys
bind = $mainMod, h, moveFocus, l
bind = $mainMod, l, moveFocus, r
# bind = $mainMod, k, moveFocus, u
# bind = $mainMod, j, moveFocus, d

# Override default SUPER+J/K bindings from sourced Omarchy defaults
unbind = $mainMod, J
unbind = $mainMod, K
bind = $mainMod, i, layoutmsg, togglesplit
bind = $mainMod, j, movefocus, l
bind = $mainMod, k, movefocus, r

# Move windows with mainMod + SHIFT + vim keys

bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r
# bind = $mainMod SHIFT, k, movewindow, u
# bind = $mainMod SHIFT, j, movewindow, d
bind = $mainMod SHIFT, j, swapwindow, l
bind = $mainMod SHIFT, k, swapwindow, r

# windowrule = workspace 5, match:class qemu
